public enum Action {
    UNKNOWN, SINGLE, DOUBLE, TRIPLE, HOMERUN, WALK, INTENTIONALWALK, 
	HITBYPITCH, ERROR, GROUNDOUT, FLYOUT, LINEOUT, POPOUT, KSWINGING, KLOOKING,
	SACRIFICE, CAUGHTSTEALING, STEAL, WILDPITCH, PASSBALL, DEFINDIF;
}